[package]
name = "pride-counter"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
reqwest = { version = "0.12.5", features = ["blocking"] }
scraper = "0.19.1"
termion = "4.0.2"
tokio = { version = "1.38.1", features = ["full"] }

[build-dependencies]
chrono = "0.4.38"
